export const location_en= [  
    ["AO", "Angola"],  
    ["AF", "Afghanistan"],  
    ["AL", "Albania"],  
    ["DZ", "Algeria"],  
    ["AD", "Andorra"],  
    ["AI", "Anguilla"],  
    ["AG", "Barbuda Antigua"],  
    ["AR", "Argentina"],  
    ["AM", "Armenia"],  
    ["AU", "Australia"],  
    ["AT", "Austria"],  
    ["AZ", "Azerbaijan"],  
    ["BS", "Bahamas"],  
    ["BH", "Bahrain"],  
    ["BD", "Bangladesh"],  
    ["BB", "Barbados"],  
    ["BY", "Belarus"],  
    ["BE", "Belgium"],  
    ["BZ", "Belize"],  
    ["BJ", "Benin"],  
    ["BM", "Bermuda Is."],  
    ["BO", "Bolivia"],  
    ["BW", "Botswana"],  
    ["BR", "Brazil"],  
    ["BN", "Brunei"],  
    ["BG", "Bulgaria"],  
    ["BF", "Burkina-faso"],  
    ["MM", "Burma"],  
    ["BI", "Burundi"],  
    ["CM", "Cameroon"],  
    ["CA", "Canada"],  
    ["CF", "Central African Republic"],  
    ["TD", "Chad"],  
    ["CL", "Chile"],  
    ["CN", "China"],  
    ["CO", "Colombia"],  
    ["CG", "Congo"],  
    ["CK", "Cook Is."],  
    ["CR", "Costa Rica"],  
    ["CU", "Cuba"],  
    ["CY", "Cyprus"],  
    ["CZ", "Czech Republic"],  
    ["DK", "Denmark"],  
    ["DJ", "Djibouti"],  
    ["DO", "Dominica Rep."],  
    ["EC", "Ecuador"],  
    ["EG", "Egypt"],  
    ["SV", "EI Salvador"],  
    ["EE", "Estonia"],  
    ["ET", "Ethiopia"],  
    ["FJ", "Fiji"],  
    ["FI", "Finland"],  
    ["FR", "France"],  
    ["GF", "French Guiana"],  
    ["GA", "Gabon"],  
    ["GM", "Gambia"],  
    ["GE", "Georgia"],  
    ["DE", "Germany"],  
    ["GH", "Ghana"],  
    ["GI", "Gibraltar"],  
    ["GR", "Greece"],  
    ["GD", "Grenada"],  
    ["GU", "Guam"],  
    ["GT", "Guatemala"],  
    ["GN", "Guinea"],  
    ["GY", "Guyana"],  
    ["HT", "Haiti"],  
    ["HN", "Honduras"],  
    ["HK", "Hongkong"],  
    ["HU", "Hungary"],  
    ["IS", "Iceland"],  
    ["IN", "India"],  
    ["ID", "Indonesia"],  
    ["IR", "Iran"],  
    ["IQ", "Iraq"],  
    ["IE", "Ireland"],  
    ["IL", "Israel"],  
    ["IT", "Italy"],  
    ["JM", "Jamaica"],  
    ["JP", "Japan"],  
    ["JO", "Jordan"],  
    ["KH", "Kampuchea (Cambodia )"],  
    ["KZ", "Kazakstan"],  
    ["KE", "Kenya"],  
    ["KR", "Korea"],  
    ["KW", "Kuwait"],  
    ["KG", "Kyrgyzstan"],  
    ["LA", "Laos"],  
    ["LV", "Latvia"],  
    ["LB", "Lebanon"],  
    ["LS", "Lesotho"],  
    ["LR", "Liberia"],  
    ["LY", "Libya"],  
    ["LI", "Liechtenstein"],  
    ["LT", "Lithuania"],  
    ["LU", "Luxembourg"],  
    ["MO", "Macao"],  
    ["MG", "Madagascar"],  
    ["MW", "Malawi"],  
