["MY", "Malaysia"],  
    ["MV", "Maldives"],  
    ["ML", "Mali"],  
    ["MT", "Malta"],  
    ["MU", "Mauritius"],  
    ["MX", "Mexico"],  
    ["MD", "Moldova"],  
    ["MC", "Monaco"],  
    ["MN", "Mongolia"],  
    ["MS", "Montserrat Is."],  
    ["MA", "Morocco"],  
    ["MZ", "Mozambique"],  
    ["NA", "Namibia"],  
    ["NR", "Nauru"],  
    ["NP", "Nepal"],  
    ["NL", "Netherlands"],  
    ["NZ", "New Zealand"],  
    ["NI", "Nicaragua"],  
    ["NE", "Niger"],  
    ["NG", "Nigeria"],  
    ["KP", "North Korea"],  
    ["NO", "Norway"],  
    ["OM", "Oman"],  
    ["PK", "Pakistan"],  
    ["PA", "Panama"],  
    ["PG", "Papua New Cuinea"],  
    ["PY", "Paraguay"],  
    ["PE", "Peru"],  
    ["PH", "Philippines"],  
    ["PL", "Poland"],  
    ["PF", "French Polynesia"],  
    ["PT", "Portugal"],  
    ["PR", "Puerto Rico"],  
    ["QA", "Qatar"],  
    ["RO", "Romania"],  
    ["RU", "Russia"],  
    ["LC", "Saint Lueia"],  
    ["VC", "Saint Vincent"],  
    ["SM", "San Marino"],  
    ["ST", "Sao Tome and Principe"],  
    ["SA", "Saudi Arabia"],  
    ["SN", "Senegal"],  
    ["SC", "Seychelles"],  
    ["SL", "Sierra Leone"],  
    ["SG", "Singapore"],  
    ["SK", "Slovakia"],  
    ["SI", "Slovenia"],  
    ["SB", "Solomon Is."],  
    ["SO", "Somali"],  
    ["ZA", "South Africa"],  
    ["ES", "Spain"],  
    ["LK", "Sri Lanka"],  
    ["SD", "Sudan"],  
    ["SR", "Suriname"],  
    ["SZ", "Swaziland"],  
    ["SE", "Sweden"],  
    ["CH", "Switzerland"],  
    ["SY", "Syria"],  
    ["TW", "Taiwan"],  
    ["TJ", "Tajikstan"],  
    ["TZ", "Tanzania"],  
    ["TH", "Thailand"],  
    ["TG", "Togo"],  
    ["TO", "Tonga"],  
    ["TT", "Trinidad and Tobago"],  
    ["TN", "Tunisia"],  
    ["TR", "Turkey"],  
    ["TM", "Turkmenistan"],  
    ["UG", "Uganda"],  
    ["UA", "Ukraine"],  
    ["AE", "United Arab Emirates"],  
    ["GB", "United Kiongdom"],  
    ["US", "United States of America"],  
    ["UY", "Uruguay"],  
    ["UZ", "Uzbekistan"],  
    ["VE", "Venezuela"],  
    ["VN", "Vietnam"],  
    ["YE", "Yemen"],  
    ["YU", "Yugoslavia"],  
    ["ZW", "Zimbabwe"],  
    ["ZR", "Zaire"],  
    ["ZM", "Zambia"]  
];  

export const location_cn= [  
    ["AO", "安哥拉"],  
    ["AF", "阿富汗"],  
    ["AL", "阿尔巴尼亚"],  
    ["DZ", "阿尔及利亚"],  
    ["AD", "安道尔共和国"],  
    ["AI", "安圭拉岛"],  
    ["AG", "安提瓜和巴布达"],  
    ["AR", "阿根廷"],  
    ["AM", "亚美尼亚"],  
    ["AU", "澳大利亚"],  
    ["AT", "奥地利"],  
    ["AZ", "阿塞拜疆"],  
    ["BS", "巴哈马"],  
    ["BH", "巴林"],  
    ["BD", "孟加拉国"],  
